# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "sedes-lambda-app"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "SedesLambdaStack"
capabilities = "CAPABILITY_IAM"
region = "us-east-2"
confirm_changeset = true
s3_bucket = "s3-sedes-despliegues"

[default.package.parameters]
s3_bucket = "s3-sedes-despliegues"
output_template_file = "packaged.yaml"
template_file = "template.yaml"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
