    services:
      usuarios:
        container_name: ms-usuarios-container
        build: 
          context: ./usuarios
          dockerfile: Dockerfile
        image: ms-usuarios-docker
        networks:
          - microservices-network
        ports:
          - "7777:7777"
    
      cursos:
        container_name: ms-cursos-container
        build: 
          context: ./cursos
          dockerfile: Dockerfile
        image: ms-cursos-docker
        networks:
          - microservices-network
        ports:
          - "9999:9999"

    networks:
      microservices-network:
        name: net-network
        driver : bridge